# Generated by Django 5.2.1 on 2025-05-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadzip',
            name='zip_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
