# Generated by Django 5.1.6 on 2025-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadzip_zip_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='tg263_primary_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='roi',
            name='tg263_reverse_order_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='roi',
            unique_together={('rtstruct', 'roi_number')},
        ),
    ]
