# Generated by Django 5.1.6 on 2025-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_roi_tg263_primary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='clean_name_match_tg263',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='roi',
            name='clean_roi_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
