# Generated by Django 5.1.6 on 2025-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_roi_clean_name_match_tg263_roi_clean_roi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='clean_name_match_tg263',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roi',
            name='clean_roi_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
