# Generated by Django 5.2.1 on 2025-05-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_roi_clean_name_match_tg263_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roi',
            old_name='clean_name_match_tg263',
            new_name='roi_of_clean_roi_name_match_tg263',
        ),
    ]
