# Generated by Django 5.2.2 on 2025-06-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_clean_name_match_tg263_roi_roi_of_clean_roi_name_match_tg263'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='add_for_radiomics',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roi',
            name='nifti_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
