# Generated by Django 5.2.2 on 2025-06-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_roi_add_for_radiomics_roi_nifti_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roi',
            old_name='nifti_file_path',
            new_name='ct_nifti_file_path',
        ),
        migrations.AddField(
            model_name='roi',
            name='roi_nifti_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
