# Generated by Django 5.2.2 on 2025-06-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_nifti_file_path_roi_ct_nifti_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roi',
            old_name='ct_nifti_file_path',
            new_name='ct_nrrd_file_path',
        ),
        migrations.RenameField(
            model_name='roi',
            old_name='roi_nifti_file_path',
            new_name='roi_nrrd_file_path',
        ),
    ]
