# Generated by Django 5.2.2 on 2025-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_ct_nifti_file_path_roi_ct_nrrd_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadzip',
            name='radiomics_data_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
