# Generated by Django 5.2.2 on 2025-06-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_radiomicfeaturemapping_remove_glcmfeatures_roi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomicfeatures',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AddField(
            model_name='radiomicfeatures',
            name='zip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uploadzip'),
        ),
    ]
