# Generated by Django 5.2.2 on 2025-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_radiomicfeatures_patient_id_radiomicfeatures_zip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomicfeaturemapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiomicfeaturemapping',
            name='feature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiomicfeaturemapping',
            name='feature_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiomicfeaturemapping',
            name='feature_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
