# Generated by Django 5.2.2 on 2025-06-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_radiomicfeatures_circularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomicfeatures',
            name='roi_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
