# Generated by Django 5.2.2 on 2025-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_radiomicfeatures_roi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomicfeatures',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
