# Generated by Django 5.2.1 on 2025-06-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_radiomicfeatures_patient_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionSession',
            fields=[
                ('extraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='radiomicfeatures',
            name='extraction_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.extractionsession'),
        ),
    ]
