# Generated by Django 5.2.1 on 2025-06-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_extractionsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomicfeatures',
            name='roi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roi'),
        ),
    ]
