# Generated by Django 5.2.4 on 2025-07-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_radiomicfeatures_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='anatomic_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='major_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='minor_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
