# Generated by Django 5.2.4 on 2025-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_roi_anatomic_group_alter_roi_major_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='fma_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
