# Generated by Django 5.0.7 on 2025-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_roi_fma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadzip',
            name='extracted_folder_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadzip',
            name='zip_file_size',
            field=models.BigIntegerField(),
        ),
    ]
